<?php

/**
 * @file
 * Changes menu trail of current node to its term's menu item
 *
 * @author Dmitriy.trt      <http://drupal.org/user/329125>
 */

function _taxonomy_menu_trails_get_settings($entity_type, $bundle, $load_default = TRUE) {
  $var_name = 'taxonomy_menu_trails_' . $entity_type . '_' . $bundle;
  $settings = variable_get($var_name);
  $var_exists = !empty($settings);
  if (empty($settings) && $load_default) {
    $settings = _taxonomy_menu_trails_defaults();
  }
  return array($settings, $var_name, $var_exists);
}

function _taxonomy_menu_trails_defaults() {
  return array(
    'selection_method' => 'first',
    'only_without_menu' => FALSE,
    'term_with_menu' => FALSE,
    'instances' => array(),
  );
}

/**
 * Implementation of hook_init().
 */
function taxonomy_menu_trails_init() {
  $item = menu_get_item();
  if (arg(0) == 'node' && is_numeric(arg(1))) {
    //TODO check more carefully
    $object = $item['page_arguments'][0];
    $settings = variable_get('taxonomy_menu_trails_node_' . $object->type, array());
    if (!empty($settings['instances'])) {
      if ($settings['only_without_menu']) {
        $has_own_menu = db_query('SELECT COUNT(*) FROM {menu_links} WHERE link_path = :path AND hidden = 0', array(':path' => $item['href']))->fetchField();
      }
      if (!$settings['only_without_menu'] || !$has_own_menu) {
        $has_terms = FALSE;
        //TODO figure out meaning of language in term reference fields
        foreach ($settings['instances'] as $field) {
          if (!empty($object->$field)) {
            $has_terms = TRUE;
            break;
          }
        }
        if ($has_terms) {
          module_load_include('inc', 'taxonomy_menu_trails');
          _taxonomy_menu_trails_process($item, 'node', $object->type, $object);
        }
      }
    }
  }
}

//TODO remove it
function taxonomy_menu_trails_form_alter(&$form, &$state, $form_id) {
  $fff = $form_id;
}

function taxonomy_menu_trails_form_field_ui_field_edit_form_alter(&$form, &$state) {
  if ($form['#instance']['entity_type'] == 'node' && $form['#field']['type'] == 'taxonomy_term_reference') {
    module_load_include('admin.inc', 'taxonomy_menu_trails');
    _taxonomy_menu_trails_alter_field_form($form);
  }
}

function taxonomy_menu_trails_form_node_type_form_alter(&$form, &$state) {
  module_load_include('admin.inc', 'taxonomy_menu_trails');
  _taxonomy_menu_trails_alter_entity_form($form, 'node', $form['#node_type']);
  $form['taxonomy_menu_trails']['#group'] = 'additional_settings';
}
