<?php

/**
 * @file
 * Changes menu trail of current node to its term's menu item
 *
 * @todo: write description for each function
 *
 * @author Dmitriy.trt      <http://drupal.org/user/329125>
 */

function _taxonomy_menu_trails_get_settings($entity_type, $bundle, $load_default = TRUE) {
  $var_name = 'taxonomy_menu_trails_' . $entity_type . '_' . $bundle;
  $settings = variable_get($var_name);
  $var_exists = !empty($settings);
  if (empty($settings) && $load_default) {
    $settings = _taxonomy_menu_trails_defaults();
  }
  return array($settings, $var_name, $var_exists);
}

function _taxonomy_menu_trails_defaults() {
  return array(
    'selection_method' => 'first',
    'only_without_menu' => FALSE,
    'tm_integration' => module_exists('taxonomy_menu'),
    'instances' => array(),
  );
}

/**
 * Implements hook_init().
 */
function taxonomy_menu_trails_init() {
  switch (arg(0)) {
    case 'node':
      if (is_numeric(arg(1))) {
        $entity_type = 'node';
        $entity_path = 'node/' . arg(1);
        $entity = node_load(arg(1));
      }
      break;
  }

  if (!empty($entity)) {
    // TODO check for active trail cache existence and process only if there is
    // no cache data for current path
    list( , , $bundle) = entity_extract_ids($entity_type, $entity);
    list($settings) = _taxonomy_menu_trails_get_settings($entity_type, $bundle, FALSE);
  
    if (!empty($settings['instances'])) {
      if ($settings['only_without_menu']) {
        $has_own_menu = db_query('SELECT COUNT(*) FROM {menu_links} WHERE link_path = :path AND hidden = 0', array(':path' => $entity_path))->fetchField();
      }
      if (!$settings['only_without_menu'] || !$has_own_menu) {
        $has_terms = FALSE;
        //TODO figure out: maybe we have to choose language in term reference fields
        foreach ($settings['instances'] as $field) {
          if (!empty($entity->$field)) {
            $has_terms = TRUE;
            break;
          }
        }
        if ($has_terms) {
          module_load_include('inc', 'taxonomy_menu_trails');
          _taxonomy_menu_trails_process($entity, $settings);
        }
      }
    }
  }
}

function taxonomy_menu_trails_form_field_ui_field_edit_form_alter(&$form, &$state) {
  if ($form['#instance']['entity_type'] == 'node' && $form['#field']['type'] == 'taxonomy_term_reference') {
    module_load_include('admin.inc', 'taxonomy_menu_trails');
    _taxonomy_menu_trails_alter_field_form($form);
  }
}

function taxonomy_menu_trails_form_node_type_form_alter(&$form, &$state) {
  module_load_include('admin.inc', 'taxonomy_menu_trails');
  _taxonomy_menu_trails_alter_entity_form($form, 'node', $form['#node_type']);
  $form['taxonomy_menu_trails']['#group'] = 'additional_settings';
  $form['taxonomy_menu_trails']['#attached'] = array(
   'js' => array(drupal_get_path('module', 'taxonomy_menu_trails') . '/js/node-type-form.js'),
  );
}

/**
 * Implements hook_entity_insert().
 */
function taxonomy_menu_trails_entity_insert($entity, $type) {
  taxonomy_menu_trails_entity_update($entity, $type);
}

/**
 * Implements hook_entity_update().
 */
function taxonomy_menu_trails_entity_update($entity, $type) {
  switch ($type) {
    case 'node':
      //TODO replace with specific cache entries deleting
      menu_cache_clear_all();
      break;
  }
}
